name: ⚙ Deploy and 🐘 Test check

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Check
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      BUILD_SOURCE_DIR: .
      BUILD_ARTIFACT_STAGING_DIR: build/
      BUILD_ARTIFACT_DESTINATION_DIR: /domains/proto.utwente.nl/deployment/uploads/
      HOST_SERVER: s176.webhostingserver.nl
      SENTRY_ORG: sa-proto
      SENTRY_PROJECT: sa-proto-website
    steps:
      - name: 🛎️ Checkout project
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: 🔍 Read .env
        run: (grep -E 'PHP_VERSION' .env.prod >> $GITHUB_ENV && cp .env.ci .env)

      - name: 🖱️ Setup PHP v${{ env.PHP_VERSION }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none

      - uses: ramsey/composer-install@v3
        with:
          composer-options: "--ignore-platform-reqs --optimize-autoloader --prefer-dist --no-dev"

      - name: 🖱️ Set Node v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: 📥 Install front-end dependencies
        run: npm ci --ignore-scripts

      - name: 🔨 build front-end
        run: npm run build

      - name: 🐘 Run PHP tests
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_CONNECTION: mysql
          DB_DATABASE: test_db
          DB_USERNAME: user
          DB_PASSWORD: password
        run: (php artisan key:generate && php artisan migrate && php artisan test)
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: laravel-failure-artifact
          path: storage/logs/laravel.log

      - name: 🗑️ Remove storage directory
        run: rm -rf storage


